//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiUberEats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comprobantes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public comprobantes()
        {
            this.pedido_det = new HashSet<pedido_det>();
        }
    
        public int pedido_id { get; set; }
        public int id { get; set; }
        public string tip_doc_ident { get; set; }
        public string num_doc_ident { get; set; }
        public string razonsocial { get; set; }
        public string direccion { get; set; }
        public string descuento { get; set; }
        public string estado_envio { get; set; }
        public string tipo_doc { get; set; }
    
        public virtual pedidos_cab pedidos_cab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedido_det> pedido_det { get; set; }
    }
}
