//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiUberEats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturacion
    {
        public int idfacturacion { get; set; }
        public Nullable<int> idtipocomprobante { get; set; }
        public Nullable<int> idtipodocumento { get; set; }
        public Nullable<int> idpedido { get; set; }
        public string nombre { get; set; }
        public string documento { get; set; }
        public string direccion { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Tipo_Comprobante Tipo_Comprobante { get; set; }
        public virtual Tipo_Documento Tipo_Documento { get; set; }
    }
}
