//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiUberEats.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdubereatsEntities : DbContext
    {
        public bdubereatsEntities()
            : base("name=bdubereatsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<comercio> comercio { get; set; }
        public virtual DbSet<comprobantes> comprobantes { get; set; }
        public virtual DbSet<formas_pago> formas_pago { get; set; }
        public virtual DbSet<fotos> fotos { get; set; }
        public virtual DbSet<notificaciones> notificaciones { get; set; }
        public virtual DbSet<paises> paises { get; set; }
        public virtual DbSet<pedido_det> pedido_det { get; set; }
        public virtual DbSet<pedido_forma_pago> pedido_forma_pago { get; set; }
        public virtual DbSet<pedidos_cab> pedidos_cab { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<promociones> promociones { get; set; }
        public virtual DbSet<repartidores> repartidores { get; set; }
        public virtual DbSet<ubicacion_cliente> ubicacion_cliente { get; set; }
    }
}
