//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiUberEats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int idpago { get; set; }
        public Nullable<int> idtipopago { get; set; }
        public Nullable<int> idtarjeta { get; set; }
        public Nullable<int> idcliente { get; set; }
        public Nullable<int> idpedido { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Pedido Pedido { get; set; }
        public virtual Tarjeta Tarjeta { get; set; }
        public virtual Tipo_Pago Tipo_Pago { get; set; }
    }
}
