//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiUberEats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido_det
    {
        public int pedido_id { get; set; }
        public string numero { get; set; }
        public int producto_id { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> precio_item { get; set; }
        public Nullable<decimal> precio_unitario { get; set; }
        public Nullable<decimal> igv { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<int> comprobante_id { get; set; }
    
        public virtual comprobantes comprobantes { get; set; }
        public virtual pedidos_cab pedidos_cab { get; set; }
        public virtual productos productos { get; set; }
    }
}
