//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiUberEats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidos_cab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pedidos_cab()
        {
            this.comprobantes = new HashSet<comprobantes>();
            this.pedido_det = new HashSet<pedido_det>();
        }
    
        public int id { get; set; }
        public string fecha_crea { get; set; }
        public string fecha_entrega { get; set; }
        public string valor_venta { get; set; }
        public string fecha_envio { get; set; }
        public Nullable<decimal> comercio_comision { get; set; }
        public Nullable<int> promocion_id { get; set; }
        public Nullable<decimal> pct_descuento_global { get; set; }
        public Nullable<decimal> monto_descuento { get; set; }
        public Nullable<int> repartidor_id { get; set; }
        public Nullable<decimal> repartidor_km_calculo { get; set; }
        public Nullable<decimal> repartidor_comision { get; set; }
        public Nullable<decimal> repartidor_tiempo_total { get; set; }
        public Nullable<decimal> repartidor_propina { get; set; }
        public string ped_estado { get; set; }
        public Nullable<int> ubicacion_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comprobantes> comprobantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedido_det> pedido_det { get; set; }
        public virtual pedido_forma_pago pedido_forma_pago { get; set; }
        public virtual promociones promociones { get; set; }
        public virtual repartidores repartidores { get; set; }
        public virtual ubicacion_cliente ubicacion_cliente { get; set; }
    }
}
