//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiUberEats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido_forma_pago
    {
        public int pedido_id { get; set; }
        public Nullable<int> forma_pago_id { get; set; }
        public Nullable<decimal> valor_pago { get; set; }
        public Nullable<decimal> vuelto { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual formas_pago formas_pago { get; set; }
        public virtual pedidos_cab pedidos_cab { get; set; }
    }
}
