//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiUberEats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class repartidores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public repartidores()
        {
            this.pedidos_cab = new HashSet<pedidos_cab>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string correo { get; set; }
        public string telefono { get; set; }
        public string cuidad { get; set; }
        public string cod_invitación { get; set; }
        public string tipo_vehiculo { get; set; }
        public string estado { get; set; }
        public Nullable<int> foto_id_antecedencites { get; set; }
        public Nullable<int> foto_id_soat { get; set; }
        public Nullable<int> foto_id_perfil { get; set; }
        public Nullable<decimal> kilometraje { get; set; }
        public Nullable<int> foto_id_licencia_con { get; set; }
        public string confirmacion { get; set; }
        public Nullable<decimal> comision { get; set; }
        public string tiempo_trabajo { get; set; }
        public Nullable<decimal> propinacion { get; set; }
        public string coordenadas { get; set; }
    
        public virtual fotos fotos { get; set; }
        public virtual fotos fotos1 { get; set; }
        public virtual fotos fotos2 { get; set; }
        public virtual fotos fotos3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedidos_cab> pedidos_cab { get; set; }
    }
}
